// This file has been generated by Specta. Do not edit this file manually.
// POST /api/activate - error response body returned from the license server.
export type ActivateErrorResponse = {
	ok: boolean,
	error: string,
	message: string,
};

// POST /api/activate - request body sent from the desktop app to the license server.
export type ActivateRequest = {
	// Gumroad license key, trimmed, validated before sending.
	licenseKey: string,
	// Machine fingerprint from `get_machine_id()`.
	machineId: string,
	// App version string, e.g. "0.1.1".
	appVersion: string,
	// Build channel: "stable" | "beta" | "nightly" | "oss".
	channel: BuildChannel,
};

// POST /api/activate - success response body returned from the license server.
export type ActivateResponse = {
	ok: boolean,
	token: string,
	expiresAt: string,
	gracePeriodEndsAt: string,
};

export type ActivationResult = {
	success: boolean,
	authState: AuthState,
	message: string | null,
};

export type AppConfig = {
	lastInputDir: string | null,
	lastOutputDir: string | null,
	lastPresetId: string | null,
	selectedRatioIds: AspectRatio[],
	selectedPresetIds: string[],
	logoPath: string | null,
	logoOpacity: number | null,
	logoPosition: LogoPosition | null,
	blur: boolean | null,
	whiteBackground: boolean | null,
	blurSigma: number | null,
	enableSubfolders: boolean | null,
	previewVolume: number | null,
};

export type AppDepsState = {
	validationRevision?: number,
	scanStatus: DependencyScanStatus,
	scanSource?: DependencyScanSource | null,
	healthStatus?: DependencyHealthStatus,
	dependencies: Partial<{ [key in DependencyId]: DependencyReport }>,
	allReady: boolean,
	lastUpdated: string,
	lastFullScanAt?: string | null,
	lastManualScanAt?: string | null,
	lastWeeklyScanAt?: string | null,
};

export type AspectRatio = "ratio9x16" | "ratio1x1" | "ratio4x5" | "ratio2x3" | "ratio16x9";

export type AspectRatioTarget = {
	id: string,
	ratio: AspectRatio,
	encoding: EncodingProfile,
};

export type AuthActivationFailedPayload = {
	reason: string,
	errorCode: string,
};

export type AuthState = {
	status: AuthStatus,
	tier: LicenseTier,
	activatedAt: string | null,
	jwtExpiresAt: string | null,
	graceExpiresAt: string | null,
	tokenHint: string | null,
	machineId: string | null,
};

export type AuthStatus = "initializing" | "credentials_found" | "validating" | "not_activated" | "activating" | "valid" | "grace_period" | "refresh_required" | "invalid" | "expired" | "offline_valid" | "machine_mismatch" | "corrupted" | "recoverable_error";

export type AuthStatusChangedPayload = {
	authState: AuthState,
};

export type BatchJobSettings = {
	targets: OutputJob[],
	outputDir: string,
	enableSubfolders?: boolean,
};

export type BatchProgress = {
	sessionId: string | null,
	totalJobs: number,
	completedJobs: number,
	failedJobs: number,
	percentage: number,
	status: BatchStatus,
	currentJobId: string | null,
	queue: FileProgress[],
	etaSeconds: number | null,
	speed: number,
	totalDurationSecs: number,
	processedDurationSecs: number,
	currentStageId: string | null,
	currentStageMessage: string | null,
};

export type BatchStatus = "idle" | "processing" | "cancelled" | "completed" | "failed";

export type BuildChannel = "stable" | "beta" | "nightly" | "oss";

export type ConversionRequestDTO = {
	input: string,
	outputDir: string,
	job: OutputJob,
};

export type CustomPreset = {
	id: string,
	name: string,
	ratio: AspectRatio,
	encoding: EncodingProfile,
};

export type DependencyHealthStatus = "unknown" | "healthy" | "degraded";

export type DependencyId = "whisper_binary" | "whisper_model" | "ffmpeg" | "ffprobe";

export type DependencyInstallEvent = {
	id: DependencyId,
	lifecycle: DependencyLifecycleStatus,
	progressPercent: number | null,
	message: string | null,
};

export type DependencyLifecycleStatus = "idle" | "checking" | "missing" | "downloading" | "verifying" | "extracting" | "installed" | "failed";

export type DependencyReport = {
	id: DependencyId,
	name: string,
	status: DependencyStatus,
	version: string | null,
	path: string | null,
	description: string,
	lastChecked: string,
	sha256Verified: boolean | null,
	expectedVersion: string | null,
	expectedSha256: string | null,
	expectedFilename: string | null,
	sourceUrl: string | null,
	updateAvailable: boolean | null,
	installedVersion: string | null,
	lifecycle: DependencyLifecycleStatus,
	lifecycleMessage: string | null,
};

export type DependencyScanSource = "first_launch" | "manual" | "weekly" | "post_download";

export type DependencyScanStatus = "not_scanned" | "scanning" | "scan_completed" | "error";

export type DependencyStatus = { status: "missing" } | { status: "installed" } | { status: "invalid"; message: string } | { status: "corrupted"; message: string } | { status: "ready" };

export type EncodingProfile = {
	crf: number,
	qualityPreset: string,
	speedPreset: string,
	audioBitrate: string,
};

export type FileProgress = {
	sessionId: string,
	jobId: string,
	filePath: string,
	ratio: AspectRatio,
	progress: number,
	status: JobStatus,
	thumbnailPath: string | null,
	durationSecs: number,
	selection: SelectionMetadata,
};

export type FileReadiness = {
	exists: boolean,
	isReadable: boolean,
	fileSizeBytes: number,
	isLocked: boolean,
	estimatedDurationSecs: number,
};

export type JobStatus = "queued" | "pending" | "processing" | "completed" | { error: string } | "cancelled";

export type LicenseTier = "community" | "pro";

/**
 *  Mirrors LicenseTier in `auth/state/license_tier.rs` but uses the wire name.
 *  These must stay in sync.
 */
export type LicenseTierWire = "community" | "pro";

export type LogoOptions = {
	enabled?: boolean,
	position: LogoPosition,
	opacity: number,
	gap: number,
	scale: number,
	path: string | null,
};

export type LogoPosition = "top_left" | "top_right" | "bottom_left" | "bottom_right";

export type OrientationInfo = {
	width: number,
	height: number,
	rotation: number,
	isVertical: boolean,
	displayWidth: number,
	displayHeight: number,
};

export type OutputFormat = "mp4" | "mov" | "webm";

export type OutputJob = {
	id: string,
	ratio: AspectRatio,
	encoding: EncodingProfile,
	effects: VideoEffectsSettings,
	platformConfig: PlatformConfig | null,
	selection: SelectionMetadata,
};

export type PlatformConfig = {
	targetWidth: number,
	targetHeight: number,
	enforceDimensions: boolean,
};

export type PlatformPreset = {
	id: string,
	name: string,
	description: string | null,
	ratio: AspectRatio,
	encoding: EncodingProfile,
	platformConfig: PlatformConfig | null,
	isBuiltin: boolean,
};

export type PreviewFitMode = "cover" | "contain";

export type PreviewLayoutRequest = {
	ratio: AspectRatio,
	targetAspectRatio: number | null,
	effects: VideoEffectsSettings,
	platformConfig: PlatformConfig | null,
};

export type PreviewRenderLayout = {
	targetWidth: number,
	targetHeight: number,
	backgroundFit: PreviewFitMode,
	foregroundFit: PreviewFitMode,
	foregroundFrameWidth: number,
	foregroundFrameHeight: number,
	blurSigma: number,
	logoWidth: number | null,
	logoGap: number | null,
	subtitle: SubtitleLayoutMetrics,
};

// POST /api/refresh - request body sent from the desktop app to the license server.
export type RefreshRequest = {
	// The current JWT.
	token: string,
	// Machine fingerprint - must match the one stored at activation.
	machineId: string,
};

export type SelectionMetadata = {
	sourceType: TargetType,
	sourceId: string,
	label: string,
};

export type StructuredError = {
	code: string,
	message: string,
};

export type SubtitleLayoutMetrics = {
	fontSize: number,
	outline: number,
	marginV: number,
	marginH: number,
	playResX: number,
	playResY: number,
};

export type TargetType = "aspectRatio" | "platform" | "custom";

export type UpdateCheckAvailableResult = {
	latestVersion: string,
	manifestUrl: string,
	rollbackVersion: string,
};

// POST /updates/check - error response body returned from the license server.
export type UpdateCheckErrorCode = "INVALID_REQUEST" | "INVALID_TOKEN" | "LICENSE_REVOKED" | "LICENSE_REFUNDED" | "ACTIVATION_REVOKED" | "UPDATES_NOT_ENTITLED" | "CHANNEL_NOT_ALLOWED" | "SERVER_ERROR";

export type UpdateCheckErrorResponse = {
	ok: boolean,
	error: UpdateCheckErrorCode,
};

// POST /updates/check - request body
export type UpdateCheckRequest = {
	// The current JWT - edge validates this before checking update entitlement.
	token: string,
	// Currently installed version.
	currentVersion: string,
};

// POST /updates/check - response body
export type UpdateCheckResponse = { allowed: boolean; latestVersion: string; manifestUrl: string; rollbackVersion: string } | { allowed: boolean };

// Update entitlement block embedded in activation/refresh responses.
export type UpdateEntitlement = {
	// ISO-8601 timestamp: this license receives updates until this date.
	entitledUntil: string,
	// Whether this is a perpetual (lifetime) license with no expiry.
	isPerpetual: boolean,
	// Whether this license is grandfathered for versions below a cutoff.
	grandfatheredBelowVersion: string | null,
};

export type UpdateEntitlementCheckResult = {
	status: UpdateEntitlementCheckStatus,
	data?: UpdateCheckAvailableResult | null,
};

export type UpdateEntitlementCheckStatus = "update_available" | "no_update" | "not_entitled" | "channel_not_allowed" | "auth_required" | "offline" | "server_error";

export type VideoEffectsSettings = {
	blur: boolean | null,
	whiteBackground: boolean | null,
	overlays: string[] | null,
	subtitles: string | null,
	colorFilter: string | null,
	blurSigma: number | null,
	removeAudio: boolean | null,
	exportSubtitles: boolean | null,
	burnSubtitles: boolean | null,
	skipExisting: boolean | null,
	outputFormat: OutputFormat | null,
	logo: LogoOptions | null,
	transform: VideoTransform | null,
};

export type VideoPresetDTO = { kind: "platform" } & PlatformPreset | { kind: "custom" } & CustomPreset;

export type VideoProgress = {
	sessionId: string,
	jobId: string,
	file: string,
	ratio: string,
	percent: number,
};

export type VideoTransform = {
	rotate?: number,
	flip_h?: boolean,
	flip_v?: boolean,
};
