// This file has been generated by Specta. Do not edit this file manually.
export type AppConfig = {
	lastInputDir: string | null,
	lastOutputDir: string | null,
	lastPresetId: string | null,
	selectedRatioIds: AspectRatio[],
	selectedPresetIds: string[],
	logoPath: string | null,
	logoOpacity: number | null,
	logoPosition: LogoPosition | null,
	blur: boolean | null,
	blurSigma: number | null,
	enableSubfolders: boolean | null,
	previewVolume: number | null,
};

export type AspectRatio = "ratio9x16" | "ratio1x1" | "ratio4x5" | "ratio2x3" | "ratio16x9";

export type AspectRatioTarget = {
	id: string,
	ratio: AspectRatio,
	encoding: EncodingProfile,
};

export type BatchJobSettings = {
	targets: OutputJob[],
	outputDir: string,
	enableSubfolders?: boolean,
};

export type BatchProgress = {
	sessionId: string | null,
	totalJobs: number,
	completedJobs: number,
	failedJobs: number,
	percentage: number,
	status: BatchStatus,
	currentJobId: string | null,
	queue: FileProgress[],
	etaSeconds: number | null,
	speed: number,
	totalDurationSecs: number,
	processedDurationSecs: number,
	currentStageId: string | null,
	currentStageMessage: string | null,
};

export type BatchStatus = "idle" | "processing" | "cancelled" | "completed" | "failed";

export type ConversionRequestDTO = {
	input: string,
	outputDir: string,
	job: OutputJob,
};

export type CustomPreset = {
	id: string,
	name: string,
	ratio: AspectRatio,
	encoding: EncodingProfile,
};

export type EncodingProfile = {
	crf: number,
	qualityPreset: string,
	speedPreset: string,
	audioBitrate: string,
};

export type FileProgress = {
	sessionId: string,
	jobId: string,
	filePath: string,
	ratio: AspectRatio,
	progress: number,
	status: JobStatus,
	thumbnailPath: string | null,
	durationSecs: number,
	selection: SelectionMetadata,
};

export type FileReadiness = {
	exists: boolean,
	isReadable: boolean,
	fileSizeBytes: number,
	isLocked: boolean,
	estimatedDurationSecs: number,
};

export type JobStatus = "queued" | "pending" | "processing" | "completed" | { error: string } | "cancelled";

export type LogoOptions = {
	enabled?: boolean,
	position: LogoPosition,
	opacity: number,
	gap: number,
	scale: number,
	path: string | null,
};

export type LogoPosition = "top_left" | "top_right" | "bottom_left" | "bottom_right";

export type OrientationInfo = {
	width: number,
	height: number,
	rotation: number,
	isVertical: boolean,
	displayWidth: number,
	displayHeight: number,
};

export type OutputFormat = "mp4" | "mov" | "webm";

export type OutputJob = {
	id: string,
	ratio: AspectRatio,
	encoding: EncodingProfile,
	effects: VideoEffectsSettings,
	platformConfig: PlatformConfig | null,
	selection: SelectionMetadata,
};

export type PlatformConfig = {
	targetWidth: number,
	targetHeight: number,
	enforceDimensions: boolean,
};

export type PlatformPreset = {
	id: string,
	name: string,
	description: string | null,
	ratio: AspectRatio,
	encoding: EncodingProfile,
	platformConfig: PlatformConfig | null,
	isBuiltin: boolean,
};

export type PreviewFitMode = "cover" | "contain";

export type PreviewLayoutRequest = {
	ratio: AspectRatio,
	targetAspectRatio: number | null,
	effects: VideoEffectsSettings,
	platformConfig: PlatformConfig | null,
};

export type PreviewRenderLayout = {
	targetWidth: number,
	targetHeight: number,
	backgroundFit: PreviewFitMode,
	foregroundFit: PreviewFitMode,
	foregroundFrameWidth: number,
	foregroundFrameHeight: number,
	blurSigma: number,
	logoWidth: number | null,
	logoGap: number | null,
	subtitle: SubtitleLayoutMetrics,
};

export type SelectionMetadata = {
	sourceType: TargetType,
	sourceId: string,
	label: string,
};

export type StructuredError = {
	code: string,
	message: string,
};

export type SubtitleLayoutMetrics = {
	fontSize: number,
	outline: number,
	marginV: number,
	marginH: number,
	playResX: number,
	playResY: number,
};

export type TargetType = "aspectRatio" | "platform" | "custom";

export type VideoEffectsSettings = {
	blur: boolean | null,
	overlays: string[] | null,
	subtitles: string | null,
	colorFilter: string | null,
	blurSigma: number | null,
	removeAudio: boolean | null,
	exportSubtitles: boolean | null,
	burnSubtitles: boolean | null,
	skipExisting: boolean | null,
	outputFormat: OutputFormat | null,
	logo: LogoOptions | null,
	transform: VideoTransform | null,
};

export type VideoProgress = {
	sessionId: string,
	jobId: string,
	file: string,
	ratio: string,
	percent: number,
};

export type VideoTransform = {
	rotate?: number,
	flip_h?: boolean,
	flip_v?: boolean,
};
