// This file has been generated by Specta. Do not edit this file manually.
export type AspectRatio = "ratio9x16" | "ratio1x1" | "ratio4x5" | "ratio2x3" | "ratio16x9";

export type BatchJobSettings = {
	targets: JobTarget[],
	output_dir: string,
	enable_subfolders?: boolean,
};

export type BatchProgress = {
	total_jobs: number,
	completed_jobs: number,
	failed_jobs: number,
	percentage: number,
	current_job_id: string | null,
};

export type ConversionOptions = {
	blur_background: boolean,
	blur_sigma: number,
	remove_audio: boolean,
	generate_subtitles?: boolean,
	burn_subtitles?: boolean,
	skip_existing: boolean,
	quality: QualityPreset,
	output_format: OutputFormat,
	logo: LogoOptions | null,
	custom_encoding_enabled: boolean,
	crf: number | null,
	preset: string | null,
	audio_bitrate: string | null,
	transform?: VideoTransform | null,
};

export type ConversionRequestDTO = {
	input: string,
	output_dir: string,
	ratio: AspectRatio,
	options: PartialConversionOptions,
	platform_config?: PlatformConfig | null,
};

export type FileProgress = {
	job_id: string,
	file_path: string,
	ratio: AspectRatio,
	progress: number,
	status: JobStatus,
};

export type FileReadiness = {
	exists: boolean,
	is_readable: boolean,
	file_size_bytes: number,
	is_locked: boolean,
	estimated_duration_secs: number,
};

export type JobStatus = "pending" | "processing" | "completed" | { error: string } | "cancelled";

export type JobTarget = {
	ratio?: AspectRatio | null,
	preset_id?: string | null,
	overrides?: PartialConversionOptions | null,
	options?: ConversionOptions | null,
	platform_config?: PlatformConfig | null,
	preset_name?: string | null,
};

export type LogoOptions = {
	enabled?: boolean,
	position: LogoPosition,
	opacity: number,
	gap: number,
	scale: number,
	path: string | null,
};

export type LogoPosition = "top_left" | "top_right" | "bottom_left" | "bottom_right";

export type OrientationInfo = {
	width: number,
	height: number,
	rotation: number,
	is_vertical: boolean,
	display_width: number,
	display_height: number,
};

export type OutputFormat = "mp4" | "mov" | "webm";

export type PartialConversionOptions = {
	blur_background: boolean | null,
	blur_sigma: number | null,
	remove_audio: boolean | null,
	generate_subtitles: boolean | null,
	burn_subtitles: boolean | null,
	skip_existing: boolean | null,
	quality: QualityPreset | null,
	output_format: OutputFormat | null,
	logo: LogoOptions | null,
	custom_encoding_enabled: boolean | null,
	crf: number | null,
	preset: string | null,
	audio_bitrate: string | null,
	transform: VideoTransform | null,
};

export type PlatformConfig = {
	target_width: number,
	target_height: number,
	enforce_dimensions: boolean,
};

export type QualityPreset = "draft" | "standard" | "high";

export type StructuredError = {
	code: string,
	message: string,
};

export type VideoPreset = {
	id: string,
	name: string,
	description: string | null,
	ratio: AspectRatio,
	options: ConversionOptions,
	logo_path: string | null,
	platform_config: PlatformConfig | null,
	is_builtin: boolean,
};

export type VideoProgress = {
	job_id: string,
	file: string,
	ratio: string,
	percent: number,
};

export type VideoTransform = {
	rotate?: number,
	flip_h?: boolean,
	flip_v?: boolean,
};
